In [ ]:
Numpy stands for numerical python, which is used to handle large , multi-dimensional array and matrices.
It offers functions for linear algebra and random number generation.
It is imp for data science and ml
It provide efficient storage and faster processing for numerical and scientic computations

In [1]:
#one -dimensional array - it is a type of  linear array
import numpy as np
a=[1,2,3,4]
arr=np.array(a)
print("list", a)
print("numpy array", arr)

list [1, 2, 3, 4]
numpy array [1 2 3 4]


In [2]:
#multi - dimensional array  - it is an array that stores data more than one dimension as rows and colums
#each element access by two indices
import numpy as np
list1=[1,2,3,4]
list2=[5,6,7,8]
list3=[9,10,11,12]
array=np.array([list1, list2, list3])
print("multi dim array", array)

multi dim array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
#parameters
#axis:   which describes the order of indexing into the array, axis0=1 dim, axis1=2dim
#shape:  number of elemnts with each axis, returned as tuples
#rank:   simply the number of dimensions it has, 1dim has rank1, 2dim has 2 ranks
import numpy as np 
array=np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])
print("Shape of the array:", array.shape)

Shape of the array: (5, 3)


In [4]:
#datatype is an example of numpy.dtype
import numpy as np
array=np.array([0,4,2])
print(array.dtype)

int32


In [5]:
#different ways of creating numpy array
#numpy.array() -> numpy array object is called ndarray, we create ndarray using this fun
import numpy as np
arr=np.array([3,4,5,5])
print("Array",arr)

Array [3 4 5 5]


In [8]:
#numpy.fromiter() -> it creates new one dim array from an iterable object.
#numpy.frontier(iterable, dtype, count=-1)
#A NumPy array that stores Unicode strings, each of length up to 2 characters.

import numpy as np
S="Sahana"
arr=np.fromiter(S,  dtype='U2')
print(arr)

arr = np.fromiter(["Sa", "ha", "na"], dtype='U2')
print(arr)


['S' 'a' 'h' 'a' 'n' 'a']
['Sa' 'ha' 'na']


In [10]:
#numpy.arange() -> that returns evenly spacecd values within a given interval
#Syntax:  numpy.arange( start , stop, step , dtype=None )
import numpy as np
np.arange(1,20,2, dtype=np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [17]:
#numpy.linspace(): This function returns evenly spaced numbers over a specified between two limits.
#Syntax: numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
import numpy as np
np.linspace(3, 10, 4,  dtype = np.int32)

array([ 3,  5,  7, 10])

In [19]:
#numpy.empty(): This function create a new array of given shape and type without #initializing value. the output generate randomly 
#Syntax: numpy.empty(shape, dtype=float, order='C')
#randomly generate
import numpy as np
np.empty([4, 3],.
         dtype = np.int32,
         order = 'C')

array([[ 83,   0,  97],
       [  0, 104,   0],
       [ 97,   0, 110],
       [  0,  97,   0]])

In [1]:
#numpy.ones(): This function is used to get a new array of given shape and type filled with ones (1).
#Syntax: numpy.ones(shape, dtype=None, order='C')
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'C')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
# numpy.zeros(): This function is used to get a new array of given shape and type filled with zeros (0). 
#Syntax: numpy.zeros(shape, dtype=None, order='C')
import numpy as np
np.zeros([4, 3], 
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
#Addition of Arrays ; where corresponding elements of arrays are added together
#add, sub, multiply,divide, power(exponential), mod(modulus)
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
addition=np.add(a, b)
print(addition)

[ 6  8 10 12]


In [26]:
#Broadcasting 
#Broadcasting in NumPy allows us to perform arithmetic operations on arrays of different shapes without reshaping them. 
#It automatically adjusts the smaller array to match the larger array's shape by

import numpy as np
array_2d=np.array([[1,2,3],[4,5,6]])
scalar=10
result=array_2d + scalar
print(result)

[[11 12 13]
 [14 15 16]]


In [27]:
import numpy as np 
arr=np.array([1,2,3]) 
res=arr+1 
print(res)

[2 3 4]


In [28]:
import numpy as np
a1=np.array([2,4,6])
a2=np.array([[1,3,5],[7,9,10]])
res=a1+a2
print(res)

[[ 3  7 11]
 [ 9 13 16]]


In [30]:
import numpy as np
ages=np.array([12,24,35,45,60,72])
age_group=np.array(["adult","minor"])
result=np.where(ages>18, age_group[0], age_group[1])
print(result)

['minor' 'adult' 'adult' 'adult' 'adult' 'adult']


In [31]:
import numpy as np
matrix=np.array(([1,2],[3,4]))
vector=np.array([10,20])
res=matrix*vector
print(res)

[[10 40]
 [30 80]]


In [33]:
food_data = np.array([[0.8, 2.9, 3.9], 
                      [52.4, 23.6, 36.5],
                      [55.2, 31.7, 23.9],
                      [14.4, 11, 4.9]])

caloric_matrix = np.array([9,4,4]) 

calorie_breakdown = food_data * caloric_matrix
print(calorie_breakdown)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


In [36]:
import numpy as np

temperatures = np.array([
    [30, 32, 34, 33, 31],  
    [25, 27, 29, 28, 26], 
    [20, 22, 24, 23, 21]  
])

corrections = np.array([1.5, -0.5, 2.0])

adjusted_temperatures = temperatures + corrections[:,np.newaxis]
print(adjusted_temperatures)
#[:, np.newaxis] is a NumPy slicing trick used to add a new axis (dimension) to an array.

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


In [37]:
#normalization of image data
#mean=0, std=1
#subtracting the mean by ensuring features hv zero mean
#scales data by dividng std by ensuring features hv unique variance
import numpy as np
image=np.array([
    [100,120,130],
    [90,110,140],
    [80,100,120]
])
mean=image.mean(axis=0)
std=image.std(axis=0)

normalized_image=(image-mean)/std
print(normalized_image)


[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


In [38]:
#centering data in machine learning
#shifiting data so that each feature has a mean 0, it is done by substracting mean of each feature from every simple

import numpy as np
data=np.array([
    [10,20],
    [15,25],
    [20,30]
])
feature_mean=data.mean(axis=0)   # [(10+15=20)/3,  (20+25+30)/3]  = [15,25]
centered_data=data-feature_mean    #10-15=-5,,,20-25=-5
print(centered_data)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
